//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeysSpec) DeepCopyInto(out *SecretKeysSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeysSpec.
func (in *SecretKeysSpec) DeepCopy() *SecretKeysSpec {
	if in == nil {
		return nil
	}
	out := new(SecretKeysSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SentryProject) DeepCopyInto(out *SentryProject) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SentryProject.
func (in *SentryProject) DeepCopy() *SentryProject {
	if in == nil {
		return nil
	}
	out := new(SentryProject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SentryProject) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SentryProjectList) DeepCopyInto(out *SentryProjectList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SentryProject, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SentryProjectList.
func (in *SentryProjectList) DeepCopy() *SentryProjectList {
	if in == nil {
		return nil
	}
	out := new(SentryProjectList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SentryProjectList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SentryProjectSpec) DeepCopyInto(out *SentryProjectSpec) {
	*out = *in
	if in.RetainOnDelete != nil {
		in, out := &in.RetainOnDelete, &out.RetainOnDelete
		*out = new(bool)
		**out = **in
	}
	if in.SecretKeys != nil {
		in, out := &in.SecretKeys, &out.SecretKeys
		*out = new(SecretKeysSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SentryProjectSpec.
func (in *SentryProjectSpec) DeepCopy() *SentryProjectSpec {
	if in == nil {
		return nil
	}
	out := new(SentryProjectSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SentryProjectStatus) DeepCopyInto(out *SentryProjectStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SentryProjectStatus.
func (in *SentryProjectStatus) DeepCopy() *SentryProjectStatus {
	if in == nil {
		return nil
	}
	out := new(SentryProjectStatus)
	in.DeepCopyInto(out)
	return out
}
