{{- if and (not .Values.existingSecret) .Values.sentryToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sentry-operator.fullname" . }}-token
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sentry-operator.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.operator.sentryTokenEnv }}: {{ .Values.sentryToken | quote }}
{{- end }}
